version: '3.4'
services:
  myapp:
    container_name: missapi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3004:3004
    volumes:
      - ./:/usr/app
      - ignore:/usr/app/node_modules/

volumes:
  ignore: